### ISSUE TITLE
How to clear previous cookies?

### ISSUE THREAD

**Issue by yeminsoe** [LinusU/flutter_web_auth#101] opened 2021-12-06 11:20 UTC

**Comment by LinusU** [comment] 2021-12-06 15:32
Duplicate of #100, #94, #40, and #24

There is no new information here that wasn't provided in #100 which you opened earlier today, why are you opening more issues?

As been stated multiple times before there is no native API that we can call in order to do this, thus there is nothing that this library can do to implement this...

**Closed by LinusU** 2021-12-06 15:32 UTC
