### ISSUE TITLE
Can't clear cache and cookies

### ISSUE THREAD

**Issue by stngcoding** [LinusU/flutter_web_auth#141] opened 2022-10-28 07:34 UTC
I need to make users select their google account when they call the function, the problem is flutter_web_auth remember the account and it keep log in automatically every single time, how can I prevent that??

**Comment by LinusU** [comment] 2022-10-28 14:08
Duplicate of #101, #100, #94, #40, and #24

Unfortunately there is nothing that we can do from the app side here, you need to work with your OAuth provider to see how this should be handled. Maybe there is a query parameter that you can append to force a profile selection or similar?

**Closed by LinusU** 2022-10-28 14:08 UTC
