### ISSUE TITLE
Getting warning on console. 

### ISSUE THREAD

**Issue by rvndsngwn** [LinusU/flutter_web_auth#126] opened 2022-06-12 19:07 UTC
```
../../flutter/.pub-cache/hosted/pub.dartlang.org/flutter_web_auth-0.4.1/lib/flutter_web_auth.dart:33:20: Warning: Operand of null-aware operation '?.' has type 'WidgetsBinding' which excludes null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../../flutter/packages/flutter/lib/src/widgets/binding.dart').
    WidgetsBinding.instance?.removeObserver(_resumedObserver); // safety measure so we never add this observer twice
                   ^
../../flutter/.pub-cache/hosted/pub.dartlang.org/flutter_web_auth-0.4.1/lib/flutter_web_auth.dart:34:20: Warning: Operand of null-aware operation '?.' has type 'WidgetsBinding' which excludes null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../../flutter/packages/flutter/lib/src/widgets/binding.dart').
    WidgetsBinding.instance?.addObserver(_resumedObserver);
                   ^
../../flutter/.pub-cache/hosted/pub.dartlang.org/flutter_web_auth-0.4.1/lib/flutter_web_auth.dart:47:20: Warning: Operand of null-aware operation '?.' has type 'WidgetsBinding' which excludes null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../../flutter/packages/flutter/lib/src/widgets/binding.dart').
    WidgetsBinding.instance?.removeObserver(_resumedObserver);
```

```
../../flutter/.pub-cache/hosted/pub.dartlang.org/flutter_web_auth-0.4.1/lib/flutter_web_auth.dart:33:20: Warning: Operand of null-aware operation '?.' has type 'WidgetsBinding' which excludes null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../../flutter/packages/flutter/lib/src/widgets/binding.dart').
    WidgetsBinding.instance?.removeObserver(_resumedObserver); // safety measure so we never add this observer twice
                   ^
../../flutter/.pub-cache/hosted/pub.dartlang.org/flutter_web_auth-0.4.1/lib/flutter_web_auth.dart:34:20: Warning: Operand of null-aware operation '?.' has type 'WidgetsBinding' which excludes null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../../flutter/packages/flutter/lib/src/widgets/binding.dart').
    WidgetsBinding.instance?.addObserver(_resumedObserver);
```

**Comment by mghase** [comment] 2022-06-12 20:58
same to me

**Comment by igoriuz** [comment] 2022-06-13 17:41
Duplicate of #117

**Closed** 2022-06-13 19:55 UTC
